import { ClerkProvider } from "@clerk/nextjs/dist/components.server";
import "./globals.css";
import { Inter } from "next/font/google";
import { UserButton } from "@clerk/nextjs";
import Search from "./components/search";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body className={inter.className}>
					<header className='flex justify-between items-center bg-stone-600 text-white p-4'>
						<p>react-server-twitter-clone</p>
						{/* <Search /> */}
						<UserButton
							showName
							appearance={{
								elements: {
									userButtonOuterIdentifier: {
										color: "white",
									},
								},
							}}
						/>
					</header>
					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}
